enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
# GLOBAL
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"  
rv-brand = "Revanced Extended"
cli-version = "v4.6.2"

[Music]
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
build-mode = "module"
include-stock = false
arch = "both"

[YouTube]
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
build-mode = "module"
excluded-patches = "'Theme' 'Alternative thumbnails' 'Enable debugging'"
include-stock = false
arch = "all"
