enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
version = "auto"
archive_dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music/"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"  
rv-brand = "Revanced Extended"
build-mode = "module"
excluded-patches = "'GmsCore support'"

[YouTube]
version = "auto"
archive_dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube/"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"  
rv-brand = "Revanced Extended"
build-mode = "module"
excluded-patches = "'Theme' 'Alternative thumbnails' 'Enable debugging' 'GmsCore support'"
